version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-downloader-bot
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
